### ISSUE TITLE
ValidationResult.newError() issue

### ISSUE THREAD

**Issue by jbeers** [coldbox-modules/cbvalidation#25]
I ran into what I think is a minor bug in ValidationResult.newError() recently. Before I made any changes I wanted to make sure that I wasn't just missing something.

The method currently looks like
```
IValidationError function newError( struct properties ){
    return duplicate( errorTemplate ).configure(argumentCollection=arguments);
}
```

This throws an error though because the the configure method expects individual paramaters and not a structure like properties. I think a fix would look something like

```
IValidationError function newError( struct properties ){
    return duplicate( errorTemplate ).configure(argumentCollection=properties);
}
````

Would this be worth pull requesting or am I doing something wrong?

**Comment by lmajano** [comment]
You are absolutely right, great observation!!

**Comment by lmajano** [comment]
fixed
