### ISSUE TITLE
UDF Validator will Fail if TargetValue is Undefined (ACF)

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbvalidation#49]
Here's how you can replicate the issue on Adobe ColdFusion. I tested with ACF 2016 (latest).

Create a new model object with a property with no default:
`property name="userType";`

Add a UDF validator to the constraints struct:
```
this.constraints = {
    "userType": { 
        required: true,
        udf: function( value, target ) {
             return true;  // just for sake of example
        }
    }
}
```

Now try validating the object.  You'll get the following error in cbvalidation\models\validators\UDFValidator.cfc
`Element TARGETVALUE is undefined in ARGUMENTS.`

I suspect the issue has to do with how ACF handles null/undefined values.  I'm just guessing, but a possible fix might be to check if `arguments.targetValue` is null, and then assign it to an empty string or JavaCast it as a null via `javaCast( "null", "" )`.

Another idea would be to stop attempting to validate a constraint if `required: true` exists and the value fails that check.  In other words, if the value doesn't exist and the value is required, don't attempt any other validators including UDF or method validators

Hope this helps!

**Comment by lmajano** [comment]
Can you confirm this behavior on ACF2018 @homestar9 we no longer support 2016
