### ISSUE TITLE
ValidationManager errors when returning validatedKeys due to sharedconstraint name

### ISSUE THREAD

**Issue by gpickin** [coldbox-modules/cbvalidation#71]
https://github.com/coldbox-modules/cbvalidation/blob/development/models/ValidationManager.cfc#L283

If you pass in a shared constraint name to `validateOrFail(target=rc, constraints="loginForm");`
The validate function handles the shared constraint name... and validates correctly.

On 283, it uses `constraints.keyExists( key )` but key in still the shared constraint name "loginForm" - it hasn't been exploded into the full struct of Constraints.

This needs to be resolved. 

Found by PowerToaster in the ortus community forum.
https://community.ortussolutions.com/t/the-function-keyexists-does-not-exist-in-the-string/9601

**Comment by bdw429s** [comment]
This issue has been mentioned on **Ortus Solutions Community**. There might be relevant details there:

https://community.ortussolutions.com/t/the-function-keyexists-does-not-exist-in-the-string/9601/2

**Comment by lmajano** [comment]
#71
closed
