### ISSUE TITLE
[Documentation]  InList Validator Should Mention It Is Not Case Sensitive

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbvalidation#82]
Normally, I would submit the change request in GitBook, but for some reason I no longer have access.  

Since the `inList` validator is not case sensitive, I think it would be a good idea to mention this in the Docs. Specifically, I would change this:

_The field must be in the included list. Note: This validator will ignore values that are null or empty strings._

to this:

_The field value must be in the included list. It is not case sensitive. Note: This validator will ignore values that are null or empty strings._

**Comment by lmajano** [comment]
Hi @homestar9 Gitbook did a relaunch and all permissions were lost. I will try adding you back again then.

**Comment by lmajano** [comment]
Ok, added you can you check please

**Comment by lmajano** [comment]
Try now

**Comment by homestar9** [comment]
That worked! Thank you!
